const fs = require("fs");

function parseDict(filePath) {
  const content = fs.readFileSync(filePath, "utf8");
  const dict = {};
  const regex = /^\s*"([^"\\]*(?:\\.[^"\\]*)*)"\s*:\s*"([^"\\]*(?:\\.[^"\\]*)*)"/gm;
  let match;
  while ((match = regex.exec(content)) !== null) {
    dict[match[1]] = match[2];
  }
  return dict;
}

const en = parseDict("lib/translations/en.ts");
const rw = parseDict("lib/translations/rw.ts");
const fr = parseDict("lib/translations/fr.ts");

// Comprehensive Kinyarwanda vocabulary dictionary for software, exams, driving school, admin, security
const rwDictionary = {
  // Common & UI
  "navo": "Navo",
  "app.name": "Navo",
  "loading": "Birimo gushakishwa...",
  "loadingEllipsis": "Tegereza gato...",
  "cancel": "Kureka",
  "save": "Kubika",
  "submit": "Kohereza",
  "close": "Gufunga",
  "back": "Gusubira inyuma",
  "next": "Komeza",
  "previous": "Ibyabanje",
  "confirm": "Kwemeza",
  "delete": "Gusiba",
  "edit": "Guhindura",
  "add": "Kongeramo",
  "send": "Kohereza",
  "message": "Ubutumwa",
  "search": "Gushakisha",
  "filter": "Gutoranya",
  "sort": "Gutondeka",
  "refresh": "Kuvugurura",
  "view": "Kureba",
  "download": "Gukuramo",
  "upload": "Kwinjiza",
  "print": "Gucapa",
  "share": "Gusangiza abandi",
  "copy": "Gukoporora",
  "success": "Byagenze neza",
  "error": "Habaye ikibazo",
  "warning": "Iburira",
  "info": "Amakuru",
  "yes": "Yego",
  "no": "Oya",
  "ok": "Birasobanutse",
  "done": "Byarangiye",
  "pending": "Bitegerejwe",
  "ongoing": "Biri Gukorwa",
  "completed": "Byarangiye Neza",
  "expired": "Byarenze Igihe",
  "invitationExpired": "Igihe cyo kwinjira cyarangiye (Expired)",
  "failed": "Ntibyatsinze",
  "active": "Birakora",
  "inactive": "Ntibikora",
  "activeLanguage": "Ururimi rurimo gukoreshwa",
  "required": "Birasabwa",
  "optional": "Si ngombwa",
  "default": "Ibisanzwe",
  "custom": "Ibyihariye",
  "settings": "Igenamiterere",
  "preferences": "Ibyo uhitamo",
  "unknown": "Ntibizwi",
  "user": "Umukoresha",
  "actions": "Ibikorwa",
  "status": "Imiterere",
  "date": "Itariki",
  "name": "Izina",
  "description": "Ibisobanuro",
  "type": "Ubwoko",
  "category": "Icyiciro",
  "all": "Byose",
  "none": "Nta na kimwe",
  "select": "Hitamo",
  "selected": "Byahiswemo",
  "total": "Igiteranyo",
  "details": "Amakuru arambuye",
  "overview": "Incamake",
  "manage": "Gucunga",
  "create": "Gukora bishya",
  "update": "Kuvugurura",
  "remove": "Kuvanaho",
  "enable": "Gufungura",
  "disable": "Gufunga",
  "enabled": "Bifunguye",
  "disabled": "Bifunze",
  "on": "Birakora",
  "off": "Byazimye",
  "reset": "Gusubiza ku ntangiriro",
  "clear": "Guhanagura",
  "apply": "Gushyira mu bikorwa",
  "saving": "Birimo kubikwa...",
  "deleting": "Birimo gusibwa...",
  "updating": "Birimo kuvugururwa...",
  "creating": "Birimo gukorwa...",
  "notAvailable": "Ntibiboneka",
  "noData": "Nta makuru ahari kugeza ubu",
  "price": "Igiciro",
  "audio": "Ijwi",
  "topicAudio": "Ijwi ry'ingingo",
  "ttsAudio": "Ijwi ryo gusoma inyandiko (TTS)",
  "ttsAudioAttached": "Ijwi ryo gusoma ryometseho (TTS)",
  "topicTTSAudio": "Ijwi ry'ingingo ryo gusoma (TTS)",
  "noTopicsYet": "Nta ngingo zirashyirwamo kugeza ubu",
  "previewNoSave": "Kureba uko bimeze (Ntibibikwa)",
  "answered": "Ibisubijwe",
  "unanswered": "Ibitarasubizwa",
  "checkAnswer": "Reba igisubizo cy'ukuri",
  "untitledQuestion": "Ikibazo kitagira umutwe",
  "chooseQuestionType": "Hitamo ubwoko bw'ikibazo",
  "addExplanation": "Ongeraho ibisobanuro birambuye",
  "lessonFolderSubtitle": "Ingingo n'ibikubiye mu isomo",
  "minTotal": "Iminota yose hamwe",
  "availableTopics": "Ingingo zihari zo kwiga",
  "noTopicsInFolder": "Nta ngingo ziri muri iri somo",
  "noTopicsInFolderDesc": "Ongeraho ingingo nshya kugira ngo abanyeshuri boroherwe no gusoma no kwimenyereza.",
  "createFirstTopic": "Kora ingingo ya mbere",
  "noTimeSet": "Nta gihe cyagenwe",
  "items": "Ibintu",
  "matches": "Ibihuye",
  "students": "Abanyeshuri",
  "noActivityYet": "Nta bikorwa birakorwa kugeza ubu",
  "suspended": "Yahagaritswe by'agateganyo",
  "desktop": "Mudasobwa (Desktop)",
  "mobile": "Telefoni igendanwa",
  "tablet": "Tabuleti (Tablet)",
  "actionFailed": "Igikorwa nticyakunze",
  "browser": "Mushakisha (Browser)",
  "hideTechnicalDetails": "Hisha amakuru y'ikoranabuhanga",
  "showTechnicalDetails": "Erekana amakuru y'ikoranabuhanga",
  "result": "Ibisubizo",
  "page": "Urupapuro",
  "of": "kuri",
  "administrators": "Abayobozi b'urubuga (Admins)",
  "suspendedUsers": "Abakoresha bahagaritswe",
  "pendingVerification": "Bitegereje kwemezwa",
  "performance": "Umusaruro n'imitsindire",
  "suspend": "Hagarika by'agateganyo",
  "activity": "Ibikorwa biheruka",
  "sendNotificationDesc": "Ohereza ubutumwa bw'integuza ku banyeshuri cyangwa abakoresha bose",
  "export": "Gusohora amakuru (Export)",
  "screenRestoredSuccess": "Ikizamini cyongeye kugarurwa muri ecran yose neza.",
  "noCategoriesAvailable": "Nta byiciro by'ibizamini bibonetse kugeza ubu",
  "waitingForScreenRestore": "Kanda hano hasi kugira ngo usubire muri ecran yose ukomeze ikizamini.",
  "archived": "Byabitswe mu bubiko (Archived)",

  // Group Exams & Challenges
  "groupExam": "Ikizamini cy'Itsinda",
  "individualExam": "Ikizamini cya Wenyine",
  "groupExamDescription": "Pima ubumenyi bwawe mu kizamini cy'amatsinda kiba ako kanya n'inshuti zawe",
  "individualExamDescription": "Kora ikizamini cy'imyitozo ku giti cyawe ku muvuduko wawe",
  "examChoiceTitle": "Hitamo Uburyo bwo Gukora Ikizamini",
  "examChoiceSubtitle": "Hitamo niba wifuza gukora ikizamini wenyine cyangwa muhatana mu itsinda",
  "startIndividualExam": "Tangira Ikizamini cya Wenyine",
  "startGroupExam": "Tangiza Ikizamini cy'Itsinda",
  "challengeExpired": "Ubutumire bw'ikizamini cy'itsinda bwarenze igihe (Expired)",
  "groupExamInvite": "Ubutumire mu kizamini cy'itsinda",
  "joinNow": "Injira ako kanya",
  "selectInvitees": "Hitamo inshuti zo gutumira mu kizamini",
  "searchCategories": "Shakisha icyiciro cy'ikizamini...",
  "noResults": "Nta bisubizo bibonetse",
  "loadingGroupExam": "Icyumba cy'ikizamini cy'itsinda kirimo gutegurwa...",
  "leaveLobby": "Sohoka mu Cyumba",
  "joinWindow": "Igihe cyo kwinjira",
  "joinedPlayers": "Abitabiriye icyumba",
  "readyToPlay": "Biteguye gutangira",
  "you": "Wowe",
  "waitingForJoin": "Gutegeza ko binjira...",
  "timeExpired": "Igihe cyarenze",
  "declinedRequests": "Ubutumire bwanzwe",
  "declined": "Yabyanze",
  "left": "Yavuyemo",
  "ready": "Yiteguye",
  "startingExam": "Ikizamini kigiye gutangira...",
  "creatorCanStartImmediately": "Uwateguye ikizamini ashobora kugitangiza igihe cyose abitabiriye bose biteguye.",
  "anyPlayerCanStart": "Umunyeshuri wese ashobora gutangiza ikizamini iyo igihe cyo kwinjira kirangiye.",
  "examRequestSent": "Ubutumire bw'ikizamini bwoherejwe neza",
  "joinRoom": "Injira mu Cyumba",
  "enterExam": "Injira mu Kizamini",
  "joinExam": "Injira mu Kizamini",
  "searchExams": "Shakisha ibizamini...",
  "viewGroupRankings": "Reba urutonde rw'amanota y'itsinda",
  "individual": "Ibya Wenyine",
  "noGroupExamHistory": "Nta kizamini cy'itsinda wari watsinda cyangwa ngo urangize kugeza ubu",
  "noIndividualExamHistory": "Nta kizamini cya wenyine wari warangiza kugeza ubu",
  "noGroupExamHint": "Tumira inshuti zawe mu kizamini cy'itsinda kugira ngo muhatane hano.",
  "friendRequestSent": "Ubusabe bw'ubucuti bwoherejwe neza",
  "friendRequestDeclined": "Ubusabe bw'ubucuti bwanzwe",
  "friendRemoved": "Yakuwe mu nshuti zawe",
  "challengeSent": "Ubutumire bw'ikizamini bwoherejwe",
  "challengeAccepted": "Ubutumire bw'ikizamini bwemejwe",
  "challengeDeclined": "Ubutumire bw'ikizamini bwanzwe",
  "waitingForHost": "Tegereza ko uwateguye ikizamini agishyira ku murongo...",
  "playersReady": "Abiteguye gutangira",
  "allPlayersReady": "Abitabiriye bose biteguye gutangira!",

  // Driver & Training
  "nationalIdHint": "Shyiramo numero y'indangamuntu y'imibare 16 iboneka ku ndangamuntu yawe.",
  "driverDashboard": "Icyicaro cy'umwarimu / umushoferi",
  "driverBookings": "Gufata gahunda yo kwiga gutwara",
  "driverStudents": "Abanyeshuri biga gutwara",
  "driverProfile": "Umwirondoro w'umwarimu wo gutwara",
  "driverEarnings": "Inyungu z'umwarimu",
  "bookDriver": "Fata gahunda yo kwiga gutwara n'umwarimu",
  "driverAvailable": "Araboneka (Ariteguye)",
  "driverBusy": "Ari mu kazi (Arahugiye)",
  "hourlyRate": "Igiciro ku isaha",
  "rating": "Amanota n'isuzuma",
  "experience": "Uburambe mu gutwara",

  // Course Progress & Navigation
  "totalEstimatedTime": "Igihe kigereranyijwe cyose",
  "viewModuleSummary": "Reba incamake y'umutwe w'isomo",
  "backToLessons": "Subira ku rutonde rw'amasomo",
  "studyTimerPausedFocusLost": "Igihe cyo kwiga cyahagaze kuko wavuye kuri iyi paji.",
  "moduleLessons": "Amasomo y'iyi ngingo",
  "lessonProgress": "Aho ugeze mu isomo",
  "day": "Umunsi",
  "moduleCreated": "Umutwe w'isomo wuzuzwe neza",
  "courseNavigation": "Gushakisha no kugendagenda mu masomo",
  "moduleCompleted": "Umutwe w'isomo warangiye neza",
  "previousLesson": "Isomo ryabanje",
  "takeModuleExam": "Kora ikizamini cy'umutwe w'isomo",
  "moduleExamPassed": "Watsinze ikizamini cy'uyu mutwe w'isomo!",
  "moduleExamFailed": "Ntiwatsinze ikizamini cy'uyu mutwe w'isomo. Ongera ugerageze.",
  "lockedModule": "Uyu mutwe w'isomo urafunze. Banza urangize ibyabanje.",
  "lockedLesson": "Iri somo rirafunze. Banza urangize amasomo yabanje.",
  "courseProgress": "Aho ugeze mu masomo",
  "topicsInLesson": "Ingingo zikubiye mu isomo",
  "markTopicDone": "Kemeza ko wamaze gusoma iyi ngingo",
  "topicTimeSpent": "Igihe wamaze wiga iyi ngingo",
  "learningTimerPaused": "Igihe cyo kwiga cyahagaze",
  "learningTimerResumed": "Igihe cyo kwiga cyongeye gukomeza",
  "activeLessonTimer": "Igihe cy'isomo ririmo kwigwa",
  "activeModuleTimer": "Igihe cy'umutwe w'isomo urimo kwigwa",

  // Security & Anti-cheating
  "fullscreenWarning1": "Ntiwemerewe kuva muri ecran yose mu gihe cy'ikizamini.",
  "fullscreenWarning2": "Iburira rya 2: Nuramuka uvuye muri ecran yose ukundi, ikizamini kizahita cyoherezwa ako kanya.",
  "fullscreenWarningFinal": "Ikizamini cyahise cyoherezwa kuko wavuye muri ecran yose inshuro zirenze izemewe.",
  "copyViolation1": "Iburira rya 1: Ntiwemerewe gukoporora (Copy) mu kizamini.",
  "copyViolation2": "Iburira rya 2: Ntiwemerewe gukoporora inyandiko mu gihe cy'ikizamini.",
  "copyViolationFinal": "Ikizamini cyahise cyoherezwa kubera gukoporora mu buryo butemewe.",
  "copyWarning1": "Iburira rya 1: Gukoporora birabujijwe.",
  "copyWarning2": "Iburira rya 2: Gukoporora birabujijwe.",
  "copyWarningFinal": "Ikizamini cyoherejwe kubera gukoporora kenshi.",
  "pasteViolation1": "Iburira rya 1: Ntiwemerewe komereza (Paste) mu kizamini.",
  "pasteViolation2": "Iburira rya 2: Ntiwemerewe komereza inyandiko mu kizamini.",
  "pasteViolationFinal": "Ikizamini cyoherejwe kubera komereza mu buryo butemewe.",
  "pasteWarning1": "Iburira rya 1: Komeka birabujijwe.",
  "pasteWarning2": "Iburira rya 2: Komeka birabujijwe.",
  "pasteWarningFinal": "Ikizamini cyoherejwe kubera komeka kenshi.",
  "examRules.strictTimer": "Igihe cy'ikizamini kigomba kubahirizwa nta guhagarara",
  "examRules.aiProhibited": "Gukoresha ubufasha bwa AI cyangwa ubundi bufasha butemewe birabujijwe",
  "examSecurity.aiDetection": "Igenzura ry'ubufasha bwa AI rirakora",
  "examSecurity.antiCheatingActive": "Umutekano wo kurwanya kwiba mu kizamini urafunguye",
  "examSecurity.fullscreenMandatory": "Gukorera ikizamini muri ecran yose ni itegeko",
  "examSecurity.windowFocusMonitored": "Gusohoka mu paji y'ikizamini biragenzurwa",
  "examSecurity.tabSwitchPenalty": "Guhindura paji bishobora gutuma ikizamini cyoherezwa",
  "examSecurity.devToolsBlocked": "Gufungura ibikoresho by'ikoranabuhanga (DevTools) birabujijwe",
  "examSecurity.extensionMonitoring": "Ubwirinzi bwa porogaramu zometse kuri mushakisha burakora",
  "violationCount.tabswitch": "Inshuro wagiye mu yindi paji",
  "violationCount.copy": "Inshuro washakaga gukoporora",
  "violationCount.paste": "Inshuro washakaga komeka",
  "violationCount.other": "Izindi nshuro wakoze amakosa y'umutekano",
  "violationCount.remaining": "Amahisa asigaye mbere yo kohereza ikizamini",
  "moduleExamInstruction.title": "Amabwiriza y'ikizamini cy'umutwe w'isomo",
  "moduleExamInstruction.timeLimit": "Ufite igihe cyagenwe cyo kurangiza iki kizamini.",
  "moduleExamInstruction.singleAttempt": "Iki kizamini gifite amanota azafatwa kuri konti yawe.",
  "moduleExamInstruction.autoGrading": "Amanota agaragara ako kanya ukimara gusoza ikizamini.",
  "moduleExamInstruction.reviewAvailable": "Uzashobora gusubiramo ibibazo watsinze n'ibyo wahushije.",
  "examInstruction.title": "Amabwiriza y'ingenzi y'ikizamini",
  "examInstruction.fullscreen": "Ikizamini kigomba gukorerwa muri ecran yose kuva gitangiye kugeza kirangiye.",
  "examInstruction.noSwitching": "Ntiwemerewe gufungura izindi paji cyangwa indi mirimo.",
  "examInstruction.timer": "Igihe kirimo kubarwa kandi kizahita cyohereza ibisubizo nicyangira.",
  "examInstruction.submission": "Iyo usoje kanda kuri 'Ohereza Ikizamini' kugira ngo ubone amanota yawe.",
  "examInstruction.security": "Amakosa yo kwica amabwiriza y'umutekano yohereza ikizamini ako kanya.",
  "examTechnical.browser": "Mushakisha yawe igomba kuba igezweho kandi ishyigikiye ecran yose.",
  "examTechnical.connection": "Reba ko ifatabuguzi rya interineti rihamye mbere yo gutangira.",
  "examTechnical.screen": "Koresha ecran ifite urumuri rukwiriye kandi itazima.",
  "examTechnical.battery": "Reba ko umuriro wa telefoni cyangwa mudasobwa uhagije.",
  "examTechnical.notifications": "Funga integuza n'ubutumwa bishobora kugutera gutakaza ikizamini.",
  "examTechnical.permissions": "Emeza uburenganzira bwose busabwa na mushakisha.",
  "fullscreenInstruction.title": "Amabwiriza ya Ecran Yose",
  "fullscreenInstruction.enter": "Kanda kuri buto yo kwinjira muri ecran yose kugira ngo utangire ikizamini.",
  "fullscreenInstruction.stay": "Guma muri ecran yose kugeza igihe cy'ikizamini kirangiye.",
  "fullscreenInstruction.warning": "Gusohoka muri ecran yose bifatwa nk'ikosa rikomeye ry'umutekano.",
  "fullscreenWarning.title": "Urubuga Ruri Hanze ya Ecran Yose",
  "fullscreenWarning.message": "Wavuye muri ecran yose y'ikizamini. Nyamuneka kanda hasi uhite usubiramo ako kanya.",
  "fullscreenWarning.reEnter": "Subira muri Ecran Yose"
};

// Automatic phrasing dictionary for untranslated english strings
function getTranslatedKinyarwanda(key, enVal) {
  if (rwDictionary[key]) return rwDictionary[key];
  if (rw[key] && rw[key] !== enVal && rw[key].trim().length > 0) return rw[key];

  let str = enVal || key;

  const exactMatches = {
    "Save Changes": "Bika Impinduka",
    "Reset to Default": "Gusubiza ku Bisanzwe",
    "Theme settings saved and applied": "Igenamiterere ry'insanganyamatsiko ryabitswe kandi ryashyizwe mu bikorwa",
    "Theme reset to default": "Insanganyamatsiko yasubijwe ku bisanzwe",
    "Theme Colors": "Amabara y'Insanganyamatsiko",
    "Customize colors for light and dark modes": "Gena amabara y'uburyo bw'urumuri n'ubw'umwijima",
    "Primary Color": "Ibara ry'Ingenzi",
    "Hover Border Color": "Ibara ry'Umurongo wo Kwerekana",
    "Glow Intensity": "Ubukana bw'Urumuri",
    "Adjust the glow effect intensity": "Gena ubukana bw'urumuri rutamurura",
    "Please select an image file": "Nyamuneka hitamo ifoto iboneye",
    "File size must be less than 5MB": "Ingano y'ifoto igomba kuba munsi ya 5MB",
    "Image uploaded successfully": "Ifoto yashyizweho neza!",
    "Failed to upload image": "Gushyiraho ifoto ntibyakunze",
    "Uploaded": "Byashyizweho",
    "Uploading...": "Birimo gushyirwaho...",
    "Click or drag image here": "Kanda cyangwa ukurure ifoto hano",
    "PNG, JPG, GIF up to 5MB": "PNG, JPG, GIF bitarengeje 5MB",
    "Failed to load system configuration": "Gufungura igenamiterere rya sisitemu ntibyakunze",
    "System Configuration": "Igenamiterere rya Sisitemu",
    "Loading configuration...": "Igenamiterere ririmo gufungurwa...",
    "Universal Exam Limit": "Imipaka Rusange y'Ibizamini",
    "Set the daily exam limit that applies to all users system-wide": "Gena umubare ntarengwa w'ibizamini abanyeshuri bakora ku munsi kuri sisitemu yose",
    "Daily Exam Limit (per user)": "Umubare ntarengwa w'ibizamini ku munsi (kuri buri mukoresha)",
    "exams per day per user": "ibizamini ku munsi kuri buri mukoresha",
    "This limit will be applied to all users unless they have individual limits set.": "Uyu mupaka uzubahirizwa ku bakoresha bose keretse abahawe imipaka yihariye.",
    "Save Exam Limit": "Bika Umupaka w'Ibizamini",
    "Exam Security Settings": "Igenamiterere ry'Umutekano w'Ibizamini",
    "Enable or disable exam security violation measures": "Fungura cyangwa ufunge ingamba zo kurwanya amakosa mu kizamini",
    "Violation Measures": "Ingamba zo Kurwanya Kwiba mu Kizamini",
    "Fullscreen enforcement, copy/paste prevention, tab switching detection": "Guhagarika gukoporora/komeka, kwinjira muri ecran yose, no kureba abava mu kizamini",
    "Current Status": "Imiterere y'Ubu",
    "Exam security features are active. Users will be monitored for violations.": "Umutekano w'ibizamini urakora. Abakora ibizamini baragenzurwa ku makosa yose.",
    "Exam security features are disabled. Users can take exams without restrictions.": "Umutekano w'ibizamini urafunze. Abanyeshuri bashobora gukora ibizamini nta nkomyi.",
    "Save Security Settings": "Bika Igenamiterere ry'Umutekano",
    "Please enter a valid number between 1 and 100": "Nyamuneka shyiramo umubare muzima hagati ya 1 na 100",
    "Exam limit updated": "Umupaka w'ibizamini wavuguruwe neza",
    "per day": "ku munsi",
    "User now has unlimited exam access": "Umukoresha ashobora gukora ibizamini bitagira umupaka",
    "Failed to update exam limit": "Kuvugurura umupaka w'ibizamini ntibyakunze",
    "Set Exam Limit": "Gena Umupaka w'Ibizamini",
    "Set the maximum number of exams this user can take per day.": "Gena umubare ntarengwa w'ibizamini uyu mukoresha ashobora gukora ku munsi.",
    "Limited Access": "Uburyo bufite Umupaka",
    "Unlimited Access": "Uburyo Butagira Umupaka",
    "User has daily exam limits": "Uyu mukoresha afite umupaka w'ibizamini ku munsi",
    "User can take unlimited exams": "Uyu mukoresha ashobora gukora ibizamini bitagira umupaka",
    "Daily Exam Limit": "Umupaka w'Ibizamini ku Munsi",
    "Enter a number between 1 and 100. Default is 5 exams per day.": "Shyiramo umubare hagati ya 1 na 100. Ibisanzwe ni ibizamini 5 ku munsi.",
    "Note:": "Icyitonderwa:",
    "The daily limit resets at midnight UTC. Users will see how many exams they have remaining.": "Umupaka wo ku munsi wongera gutangira saa sita z'ijoro (UTC). Abakoresha babona ibizamini basigaje.",
    "Students": "Abanyeshuri",
    "Course Management": "Gucunga Amasomo",
    "Course Studio": "Icyumba cy'Amasomo (Studio)",
    "Retake Requests": "Ubusabe bwo Gusubiramo Ikizamini",
    "Exams": "Ibizamini",
    "Notifications": "Integuza",
    "Feature": "Igice cy'Urubuga",
    "None": "Nta na kimwe",
    "Read Only": "Gusoma Gusa (Read Only)",
    "Read + Write": "Gusoma no Guhindura (Read + Write)",
    "Full access": "Uburenganzira Busesuye",
    "No access": "Nta burenganzira",
    "Drivers": "Abarimu n'Abashoferi",
    "Manage Drivers": "Gucunga Abarimu n'Abashoferi",
    "Manage Reports": "Gucunga Raporo n'Ibirego",
    "Filed by": "Yatanzwe na",
    "Safe": "Umutekano Wifashe Neza",
    "Critical": "Ikibazo Gikomeye",
    "Admin Management": "Ubuyobozi bw'Urubuga",
    "Register and manage admins with granular permissions": "Kwandika no gucunga abayobozi bafite uburenganzira bwihariye",
    "The new admin will receive an email invite to set their password": "Umuyobozi mushya azahabwa ubutumire bwo gushyiraho ijambo ry'ibanga kuri imeyili",
    "Send Invite": "Ohereza Ubutumire",
    "Admin invited successfully": "Umuyobozi yatumirwe neza!",
    "Failed to invite admin": "Gutumira umuyobozi ntibyakunze",
    "Failed to load admins": "Gufungura urutonde rw'abayobozi ntibyakunze",
    "No admins registered yet": "Nta bayobozi banditswe kugeza ubu",
    "Edit Permissions": "Hindura Uburenganzira",
    "Failed to load permissions": "Gufungura uburenganzira ntibyakunze",
    "Admin permissions updated": "Uburenganzira bw'umuyobozi bwaguruye neza",
    "Failed to update permissions": "Kuvugurura uburenganzira ntibyakunze",
    "Remove Admin": "Kura mu Bayobozi",
    "Are you sure you want to remove this admin? This action cannot be undone.": "Koko urashaka gukura uyu muntu mu buyobozi? Iki gikorwa ntigisubizwa inyuma.",
    "Admin removed": "Umuyobozi yakuweho neza",
    "Failed to remove admin": "Gukuraho umuyobozi ntibyakunze",
    "No permissions set": "Nta burenganzira bwashyizweho",
    "sections": "ibyiciro",
    "Look Up ID": "Shakisha Indangamuntu",
    "Enter any 16-digit National ID to look up...": "Shyiramo numero y'indangamuntu y'imibare 16...",
    "No users with National ID found": "Nta mukoresha ufite iyo ndangamuntu wabonetse",
    "Your selection": "Igisubizo Wahisemo",
    "Not answered": "Nticyasubijwe",
    "Back to Dashboard": "Subira Ahabanza",
    "Review Mode": "Gusubiramo Ikizamini",
    "Duration": "Igihe Cyakoreshejwe",
    "Category": "Icyiciro",
    "Status": "Imiterere",
    "Completed": "Cyasojwe Neza",
    "Abandoned": "Cyasizwe Hagati",
    "English": "Icyongereza",
    "Kinyarwanda": "Ikinyarwanda",
    "Français": "Igifaransa",
    "Profile picture updated successfully": "Ifoto y'umwirondoro yavuguruwe neza!",
    "Failed to update profile picture": "Kuvugurura ifoto y'umwirondoro ntibyakunze",
    "Profile picture removed successfully": "Ifoto y'umwirondoro yakuweho neza",
    "Failed to remove profile picture": "Gukuraho ifoto y'umwirondoro ntibyakunze",
    "Password updated successfully": "Ijambo ry'ibanga ryahinduwe neza!",
    "Failed to update password": "Guhindura ijambo ry'ibanga ntibyakunze",
    "Member": "Umunyamuryango",
    "View Profile": "Reba Umwirondoro",
    "Change Photo": "Hindura Ifoto",
    "Restore Google": "Garura iya Google",
    "Search settings...": "Shakisha mu igenamiterere...",
    "Account": "Konti",
    "Profile Settings": "Igenamiterere ry'Umwirondoro",
    "Manage your profile information": "Genzura amakuru y'umwirondoro wawe",
    "Not Set": "Ntibirashyirwaho",
    "Personal Info": "Amakuru Yitekerereje",
    "Incomplete": "Ntibiruzura",
    "Username": "Izina ry'umukoresha",
    "Edit Profile": "Hindura Umwirondoro",
    "Privacy & Data": "Ibanga n'Amakuru Bwite",
    "Export, delete, retention": "Gusohora amakuru, gusiba, no kubika amakuru",
    "Download Data": "Gukuramo Amakuru Bwite",
    "User not found": "Umukoresha ntabonetse",
    "Data exported successfully": "Amakuru yasohotse neza",
    "Failed to export data": "Gusohora amakuru ntibyakunze"
  };

  if (exactMatches[str]) return exactMatches[str];

  return str;
}

// Generate unified list of keys
const allKeys = new Set([...Object.keys(en), ...Object.keys(rw), ...Object.keys(fr), ...Object.keys(rwDictionary)]);

const outputRW = {};
const outputEN = {};
const outputFR = {};

for (const key of allKeys) {
  // EN
  outputEN[key] = en[key] || rwDictionary[key] || key;

  // FR
  outputFR[key] = fr[key] || outputEN[key];

  // RW
  outputRW[key] = getTranslatedKinyarwanda(key, outputEN[key]);
}

function serializeDict(dict, name) {
  const sortedKeys = Object.keys(dict).sort();
  let code = `const ${name}: Record<string, string> = {\n`;
  for (const k of sortedKeys) {
    const val = dict[k] || "";
    const escapedVal = val.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
    code += `  "${k}": "${escapedVal}",\n`;
  }
  code += `};\n\nexport default ${name};\n`;
  return code;
}

fs.writeFileSync("lib/translations/rw.ts", serializeDict(outputRW, "rw"));
fs.writeFileSync("lib/translations/en.ts", serializeDict(outputEN, "en"));
fs.writeFileSync("lib/translations/fr.ts", serializeDict(outputFR, "fr"));

console.log("Successfully rebuilt all 3 translation files:", {
  rwCount: Object.keys(outputRW).length,
  enCount: Object.keys(outputEN).length,
  frCount: Object.keys(outputFR).length
});
